# Generated by Django 5.2.4 on 2025-07-19 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EKM', 'Ernakulam'), ('ALPY', 'Alappuzha'), ('KLM', 'Kollam')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('vehicle_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ferries',
            },
        ),
        migrations.CreateModel(
            name='FerryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PASSENGER', 'Passenger Ferry'), ('RORO', 'RoRo Ferry'), ('VEGA', 'Vega Boat')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('base_price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('features', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FerrySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('operating_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.ferry')),
            ],
            options={
                'ordering': ['route', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=10)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('booking_date', models.DateField()),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('SENIOR', 'Senior Citizen')], default='ADULT', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_registration', models.CharField(blank=True, max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='home.ferryschedule')),
                ('ferry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ferrytype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FerryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='home.district')),
            ],
            options={
                'ordering': ['district', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ferry',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ferrystation'),
        ),
        migrations.AddField(
            model_name='ferry',
            name='ferry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferries', to='home.ferrytype'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='home.ferrystation')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='home.ferrystation')),
                ('supported_ferry_types', models.ManyToManyField(related_name='available_routes', to='home.ferrytype')),
            ],
        ),
        migrations.AddField(
            model_name='ferryschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='home.route'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='home.booking')),
                ('ferry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='home.ferrytype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='home.route')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('assigned_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_masters', to='home.ferrystation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_master_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Motorcycle'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('AUTO', 'Auto Rickshaw')], max_length=20)),
                ('vehicle_registration', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_license', models.CharField(max_length=30)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='home.booking')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('ferry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_prices', to='home.ferrytype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='home.route')),
            ],
            options={
                'unique_together': {('route', 'ferry_type')},
            },
        ),
    ]
